<?xml version='1.0' encoding='UTF-8' standalone='no'?>
<doxygen xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="compound.xsd" version="1.8.17">
  <compounddef id="classKDL_1_1Joint_1_1joint__type__exception" kind="class" language="C++" prot="private">
    <compoundname>KDL::Joint::joint_type_exception</compoundname>
    <basecompoundref refid="cpp/error/exception" prot="public" virt="non-virtual">std::exception</basecompoundref>
      <sectiondef kind="private-func">
      <memberdef kind="function" id="classKDL_1_1Joint_1_1joint__type__exception_1af66c016d978d126ddbc2aaccd97ebd32" prot="private" static="no" const="yes" explicit="no" inline="yes" virt="virtual">
        <type>const char *</type>
        <definition>virtual const char* KDL::Joint::joint_type_exception::what</definition>
        <argsstring>() const</argsstring>
        <name>what</name>
        <exceptions> throw ()</exceptions>
        <briefdescription>
        </briefdescription>
        <detaileddescription>
        </detaileddescription>
        <inbodydescription>
        </inbodydescription>
        <location file="src/joint.hpp" line="282" column="20" bodyfile="src/joint.hpp" bodystart="282" bodyend="283"/>
      </memberdef>
      </sectiondef>
    <briefdescription>
    </briefdescription>
    <detaileddescription>
    </detaileddescription>
    <inheritancegraph>
      <node id="1">
        <label>KDL::Joint::joint_type_exception</label>
        <link refid="classKDL_1_1Joint_1_1joint__type__exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>std::exception</label>
        <link refid="cpp/error/exception" external="/home/docker/.local/lib/python3.8/site-packages/catkin_tools_document/external/cppreference-doxygen-web.tag.xml"/>
      </node>
    </inheritancegraph>
    <collaborationgraph>
      <node id="1">
        <label>KDL::Joint::joint_type_exception</label>
        <link refid="classKDL_1_1Joint_1_1joint__type__exception"/>
        <childnode refid="2" relation="public-inheritance">
        </childnode>
      </node>
      <node id="2">
        <label>std::exception</label>
        <link refid="cpp/error/exception" external="/home/docker/.local/lib/python3.8/site-packages/catkin_tools_document/external/cppreference-doxygen-web.tag.xml"/>
      </node>
    </collaborationgraph>
    <location file="src/joint.hpp" line="281" column="55" bodyfile="src/joint.hpp" bodystart="281" bodyend="284"/>
    <listofallmembers>
      <member refid="cpp/error/exception/exception_1" prot="public" virt="non-virtual"><scope>KDL::Joint::joint_type_exception</scope><name>exception</name></member>
      <member refid="cpp/error/exception/operator=_1" prot="public" virt="non-virtual"><scope>KDL::Joint::joint_type_exception</scope><name>operator=</name></member>
      <member refid="classKDL_1_1Joint_1_1joint__type__exception_1af66c016d978d126ddbc2aaccd97ebd32" prot="private" virt="virtual"><scope>KDL::Joint::joint_type_exception</scope><name>what</name></member>
      <member refid="cpp/error/exception/what_1" prot="public" virt="non-virtual" ambiguityscope="std::exception::"><scope>KDL::Joint::joint_type_exception</scope><name>what</name></member>
      <member refid="cpp/error/exception/~exception_1" prot="public" virt="non-virtual"><scope>KDL::Joint::joint_type_exception</scope><name>~exception</name></member>
    </listofallmembers>
  </compounddef>
</doxygen>
